otc:
  obs:
    bucket-name: local
local:
  file-storage: /tmp/.local-storage
error:
  nodes:
    active: true
spring:
  config:
    import: "kubernetes:,configtree:/etc/secrets/*/"
  data:
    redis:
      host: redis
      username: redis
