otc:
  obs:
    bucket-name: neuris-document-storage-uat

spring:
  config:
    import: "kubernetes:,configtree:/etc/secrets/*/"
  data:
    redis:
      host: redis
      username: redis

logging:
  level:
    de.bund.digitalservice.ris.caselaw.config.CaselawRequestLoggingFilter: DEBUG

sentry:
  dsn: ${SENTRY_DSN}
  environment: uat
  traces-sample-rate: 0.01

neuris:
  environment: uat
  portalUrl: https://ris-portal.uat.ds4g.net
  document-number-patterns:
    BGH: KORE7****1YYY # results in e.g. KORE 7 0001 1024
    BVerfG: KVRE*****YY41 # results in e.g. KVRE 00001 24 41
    BVerwG: WBRE6****YYYY
    BSG: KSRE1******YY
    DS: XXRE0******YY
    DS-Anh: XXAH0******YY
    CC-RIS: XXRE1******YY
    CC-RIS-Anh: XXAH1******YY
    BFH: STRE1YYY2****
    BFH-Anh: STAH1YYY2****
    BPatG: MPRE7******YY
    BAG: KARE7****1YYY
